# fly.toml file generated for ensayo-db on 2021-04-25T23:59:30+02:00

app = "ensayo-db"

kill_signal = "SIGTERM"
kill_timeout = 300
services = []

[checks]

  [checks.pg]
    args = ["pg"]
    command = "flycheck"
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
    type = "script"

  [checks.role]
    args = ["role"]
    command = "flycheck"
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
    type = "script"

  [checks.vm]
    args = ["vm"]
    command = "flycheck"
    grace_period = "1s"
    interval = "1m"
    restart_limit = 0
    timeout = "10s"
    type = "script"

[env]
  PRIMARY_REGION = "ams"

[experimental]
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "pg_data"
